version: "2"
linters:
  enable:
    - gosec
    - testifylint
  settings:
    gosec:
      severity: medium
      confidence: medium
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - gen
      - internal/db
      - web
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
