import React from 'react';
import { Link } from 'react-router-dom';

const scalarHtml = `<!doctype html>
<html>
  <head>
    <title>Petstore API Reference - OpenAPI</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      body {
        margin: 0;
        padding: 0;
        height: 100vh;
        overflow: hidden;
      }
    </style>
  </head>
  <body>
    <script
      id="api-reference"
      data-url="/openapi.yaml"
      data-configuration='{"theme":"purple","darkMode":true,"layout":"modern","showSidebar":true,"servers":[{"url":"https://localhost:8080","description":"Local API Server (TLS)"},{"url":"http://localhost:8080","description":"Local API Server (Cleartext)"}]}'
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>`;

export const Docs: React.FC = () => {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100vh', width: '100%', overflow: 'hidden' }}>
      <div
        style={{
          background: 'var(--bg-secondary)',
          color: 'var(--text-primary)',
          padding: '0.6rem 1.2rem',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          borderBottom: '1px solid var(--border-primary)',
          fontSize: '0.85rem',
          flexShrink: 0,
        }}
      >
        <Link to="/" style={{ color: 'var(--accent-secondary)', textDecoration: 'none', fontWeight: 500 }}>
          ← Back to Petstore UI
        </Link>
        <div>
          <span>OpenAPI 3.1 (Generated by protoc-gen-connect-openapi)</span>
          <span style={{ margin: '0 0.5rem' }}>•</span>
          <a
            href="/openapi.yaml"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: 'var(--accent-secondary)', textDecoration: 'none' }}
          >
            Download openapi.yaml
          </a>
        </div>
      </div>
      <iframe
        title="Scalar API Reference"
        srcDoc={scalarHtml}
        style={{
          flex: 1,
          width: '100%',
          height: '100%',
          border: 'none',
        }}
      />
    </div>
  );
};
