import React from 'react';
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import '@testing-library/jest-dom/vitest';
import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { TransportProvider } from '@connectrpc/connect-query';
import { BrowserRouter, MemoryRouter, Routes, Route } from 'react-router-dom';
import { startFauxRPC, FauxRPCServer } from './fauxrpc';
import { ConnectError, Code } from '@connectrpc/connect';
import { createTransport, getPetClient } from '../lib/client';
import { PetList } from '../pages/PetList';
import { PetDetails } from '../pages/PetDetails';
import { CreatePet } from '../pages/CreatePet';

describe('Frontend tests with FauxRPC mock server', () => {
  let fauxrpc: FauxRPCServer;
  let transport: ReturnType<typeof createTransport>;
  let queryClient: QueryClient;

  beforeAll(async () => {
    fauxrpc = await startFauxRPC();
    transport = createTransport(fauxrpc.url);
  }, 10000);

  afterAll(async () => {
    await fauxrpc?.stop();
  });

  const renderWithProviders = (ui: React.ReactElement) => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: {
          retry: false,
          staleTime: 0,
        },
      },
    });

    return render(
      <TransportProvider transport={transport}>
        <QueryClientProvider client={queryClient}>
          {ui}
        </QueryClientProvider>
      </TransportProvider>
    );
  };

  it('connects to FauxRPC and retrieves mock pets via PetService client', async () => {
    const client = getPetClient(transport);
    const resp = await client.listPets({ pageSize: 5 });

    expect(resp).toBeDefined();
    expect(resp.pets).toBeDefined();
    expect(Array.isArray(resp.pets)).toBe(true);
    expect(resp.pets.length).toBeGreaterThan(0);

    const firstPet = resp.pets[0];
    expect(firstPet.id).toBeTruthy();
    expect(firstPet.name).toBeTruthy();
    expect(firstPet.species).toBeTruthy();
  });

  it('renders PetList page and displays mock pets generated by FauxRPC', async () => {
    renderWithProviders(
      <BrowserRouter>
        <PetList />
      </BrowserRouter>
    );

    // Header exists
    expect(screen.getByText('Pets Directory')).toBeInTheDocument();

    // Wait for mock pets from FauxRPC to be rendered into the DOM
    await waitFor(() => {
      const names = document.querySelectorAll('.pet-name');
      expect(names.length).toBeGreaterThan(0);
    }, { timeout: 8000 });

    const petNames = document.querySelectorAll('.pet-name');
    const firstPetName = petNames[0].textContent || '';
    expect(firstPetName).toBeTruthy();

    // Verify search filter input exists and is functional
    const searchInput = screen.getByPlaceholderText(/search by name, species, or tags/i);
    expect(searchInput).toBeInTheDocument();

    fireEvent.change(searchInput, { target: { value: 'non-matching-query-xyz-123' } });
    await waitFor(() => {
      expect(screen.getByText(/no pets match your current filter or search criteria/i)).toBeInTheDocument();
    });

    // Clear search and verify pets return
    fireEvent.change(searchInput, { target: { value: '' } });
    await waitFor(() => {
      expect(screen.getByText(firstPetName)).toBeInTheDocument();
    });
  });

  it('renders PetDetails page for a mock pet from FauxRPC', async () => {
    const client = getPetClient(transport);
    const listResp = await client.listPets({ pageSize: 1 });
    const pet = listResp.pets[0];
    const petId = pet?.id || 'mock-id-123';

    renderWithProviders(
      <MemoryRouter initialEntries={[`/pets/${petId}`]}>
        <Routes>
          <Route path="/pets/:id" element={<PetDetails />} />
        </Routes>
      </MemoryRouter>
    );

    // Verify loaded pet details
    await waitFor(
      () => {
        expect(screen.getByRole('heading', { name: 'Pet Information' })).toBeInTheDocument();
        expect(screen.getByRole('heading', { name: 'Audit & Identity' })).toBeInTheDocument();
        expect(screen.getByRole('button', { name: /Upload Photo/i })).toBeInTheDocument();
      },
      { timeout: 8000 }
    );
  });

  it('renders CreatePet page and handles form controls', async () => {
    renderWithProviders(
      <BrowserRouter>
        <CreatePet />
      </BrowserRouter>
    );

    expect(screen.getByText('Add New Pet')).toBeInTheDocument();
    expect(screen.getByLabelText(/Name/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/Species/i)).toBeInTheDocument();
    expect(screen.getByLabelText('Birth Date')).toBeInTheDocument();
    expect(screen.getByLabelText(/estimate/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/Status/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/Upload Photo/i)).toBeInTheDocument();

    // Verify submit button exists
    expect(screen.getByRole('button', { name: /Create Pet/i })).toBeInTheDocument();
  });
});

describe('Frontend tests with FauxRPC failure stubs', () => {
  let fauxrpc: FauxRPCServer;
  let transport: ReturnType<typeof createTransport>;

  beforeAll(async () => {
    fauxrpc = await startFauxRPC('stubs/failures');
    transport = createTransport(fauxrpc.url);
  }, 10000);

  afterAll(async () => {
    await fauxrpc?.stop();
  });

  it('handles distinct RPC failures from failure stubs', async () => {
    const client = getPetClient(transport);

    // ListPets returns UNAVAILABLE (code 14)
    try {
      await client.listPets({});
      expect.fail('expected listPets to fail');
    } catch (err) {
      expect((err as ConnectError).code).toBe(Code.Unavailable);
    }

    // GetPet returns NOT_FOUND (code 5)
    try {
      await client.getPet({ id: '11111111-1111-1111-1111-111111111111' });
      expect.fail('expected getPet to fail');
    } catch (err) {
      expect((err as ConnectError).code).toBe(Code.NotFound);
    }

    // CreatePet returns ALREADY_EXISTS (code 6)
    try {
      await client.createPet({ name: 'Fido', species: 'Dog', birthDate: '2023-01-01' });
      expect.fail('expected createPet to fail');
    } catch (err) {
      expect((err as ConnectError).code).toBe(Code.AlreadyExists);
    }

    // DeletePet returns PERMISSION_DENIED (code 7)
    try {
      await client.deletePet({ id: '11111111-1111-1111-1111-111111111111' });
      expect.fail('expected deletePet to fail');
    } catch (err) {
      expect((err as ConnectError).code).toBe(Code.PermissionDenied);
    }
  });
});

