// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pet_photos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPetPhoto = `-- name: CreatePetPhoto :one
INSERT INTO pet_photos (
    pet_id, data, mime_type, size_bytes
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, pet_id, mime_type, size_bytes, created_at
`

type CreatePetPhotoParams struct {
	PetID     pgtype.UUID `json:"pet_id"`
	Data      []byte      `json:"data"`
	MimeType  string      `json:"mime_type"`
	SizeBytes int32       `json:"size_bytes"`
}

type CreatePetPhotoRow struct {
	ID        pgtype.UUID        `json:"id"`
	PetID     pgtype.UUID        `json:"pet_id"`
	MimeType  string             `json:"mime_type"`
	SizeBytes int32              `json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePetPhoto(ctx context.Context, arg CreatePetPhotoParams) (CreatePetPhotoRow, error) {
	row := q.db.QueryRow(ctx, createPetPhoto,
		arg.PetID,
		arg.Data,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i CreatePetPhotoRow
	err := row.Scan(
		&i.ID,
		&i.PetID,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deletePetPhoto = `-- name: DeletePetPhoto :one
DELETE FROM pet_photos
WHERE id = $1
RETURNING pet_id
`

func (q *Queries) DeletePetPhoto(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deletePetPhoto, id)
	var pet_id pgtype.UUID
	err := row.Scan(&pet_id)
	return pet_id, err
}

const getPetPhoto = `-- name: GetPetPhoto :one
SELECT id, pet_id, data, mime_type, size_bytes, created_at
FROM pet_photos
WHERE id = $1
`

func (q *Queries) GetPetPhoto(ctx context.Context, id pgtype.UUID) (PetPhoto, error) {
	row := q.db.QueryRow(ctx, getPetPhoto, id)
	var i PetPhoto
	err := row.Scan(
		&i.ID,
		&i.PetID,
		&i.Data,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listPetPhotos = `-- name: ListPetPhotos :many
SELECT id, pet_id, mime_type, size_bytes, created_at
FROM pet_photos
WHERE pet_id = $1
ORDER BY created_at DESC
`

type ListPetPhotosRow struct {
	ID        pgtype.UUID        `json:"id"`
	PetID     pgtype.UUID        `json:"pet_id"`
	MimeType  string             `json:"mime_type"`
	SizeBytes int32              `json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPetPhotos(ctx context.Context, petID pgtype.UUID) ([]ListPetPhotosRow, error) {
	rows, err := q.db.Query(ctx, listPetPhotos, petID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPetPhotosRow{}
	for rows.Next() {
		var i ListPetPhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.PetID,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosForPets = `-- name: ListPhotosForPets :many
SELECT id, pet_id, mime_type, size_bytes, created_at
FROM pet_photos
WHERE pet_id = ANY($1::uuid[])
ORDER BY created_at DESC
`

type ListPhotosForPetsRow struct {
	ID        pgtype.UUID        `json:"id"`
	PetID     pgtype.UUID        `json:"pet_id"`
	MimeType  string             `json:"mime_type"`
	SizeBytes int32              `json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPhotosForPets(ctx context.Context, petIds []pgtype.UUID) ([]ListPhotosForPetsRow, error) {
	rows, err := q.db.Query(ctx, listPhotosForPets, petIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPhotosForPetsRow{}
	for rows.Next() {
		var i ListPhotosForPetsRow
		if err := rows.Scan(
			&i.ID,
			&i.PetID,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
