// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pet_photos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPetPhotoURL = `-- name: AddPetPhotoURL :one
UPDATE pets
SET photo_urls = array_append(photo_urls, $3::text),
    modified_at = NOW(),
    modified_by = $2
WHERE id = $1
RETURNING id, name, species, birth_date, birth_date_estimated, status, photo_urls, tags, created_at, modified_at, created_by, modified_by
`

type AddPetPhotoURLParams struct {
	ID         pgtype.UUID `json:"id"`
	ModifiedBy string      `json:"modified_by"`
	PhotoUrl   string      `json:"photo_url"`
}

func (q *Queries) AddPetPhotoURL(ctx context.Context, arg AddPetPhotoURLParams) (Pet, error) {
	row := q.db.QueryRow(ctx, addPetPhotoURL, arg.ID, arg.ModifiedBy, arg.PhotoUrl)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Species,
		&i.BirthDate,
		&i.BirthDateEstimated,
		&i.Status,
		&i.PhotoUrls,
		&i.Tags,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CreatedBy,
		&i.ModifiedBy,
	)
	return i, err
}

const createPetPhoto = `-- name: CreatePetPhoto :one
INSERT INTO pet_photos (
    pet_id, data, mime_type, size_bytes
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, pet_id, mime_type, size_bytes, created_at
`

type CreatePetPhotoParams struct {
	PetID     pgtype.UUID `json:"pet_id"`
	Data      []byte      `json:"data"`
	MimeType  string      `json:"mime_type"`
	SizeBytes int32       `json:"size_bytes"`
}

type CreatePetPhotoRow struct {
	ID        pgtype.UUID        `json:"id"`
	PetID     pgtype.UUID        `json:"pet_id"`
	MimeType  string             `json:"mime_type"`
	SizeBytes int32              `json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePetPhoto(ctx context.Context, arg CreatePetPhotoParams) (CreatePetPhotoRow, error) {
	row := q.db.QueryRow(ctx, createPetPhoto,
		arg.PetID,
		arg.Data,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i CreatePetPhotoRow
	err := row.Scan(
		&i.ID,
		&i.PetID,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deletePetPhoto = `-- name: DeletePetPhoto :one
DELETE FROM pet_photos
WHERE id = $1
RETURNING pet_id
`

func (q *Queries) DeletePetPhoto(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deletePetPhoto, id)
	var pet_id pgtype.UUID
	err := row.Scan(&pet_id)
	return pet_id, err
}

const getPetPhoto = `-- name: GetPetPhoto :one
SELECT id, pet_id, data, mime_type, size_bytes, created_at
FROM pet_photos
WHERE id = $1
`

func (q *Queries) GetPetPhoto(ctx context.Context, id pgtype.UUID) (PetPhoto, error) {
	row := q.db.QueryRow(ctx, getPetPhoto, id)
	var i PetPhoto
	err := row.Scan(
		&i.ID,
		&i.PetID,
		&i.Data,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listPetPhotos = `-- name: ListPetPhotos :many
SELECT id, pet_id, mime_type, size_bytes, created_at
FROM pet_photos
WHERE pet_id = $1
ORDER BY created_at DESC
`

type ListPetPhotosRow struct {
	ID        pgtype.UUID        `json:"id"`
	PetID     pgtype.UUID        `json:"pet_id"`
	MimeType  string             `json:"mime_type"`
	SizeBytes int32              `json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPetPhotos(ctx context.Context, petID pgtype.UUID) ([]ListPetPhotosRow, error) {
	rows, err := q.db.Query(ctx, listPetPhotos, petID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPetPhotosRow{}
	for rows.Next() {
		var i ListPetPhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.PetID,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
