// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPet = `-- name: CreatePet :one
INSERT INTO pets (
    name, species, birth_date, birth_date_estimated, status, photo_urls, tags, created_at, modified_at, created_by, modified_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW(), $8, $9
)
RETURNING id, name, species, birth_date, birth_date_estimated, status, tags, created_at, modified_at, created_by, modified_by, photo_urls
`

type CreatePetParams struct {
	Name               string      `json:"name"`
	Species            string      `json:"species"`
	BirthDate          pgtype.Date `json:"birth_date"`
	BirthDateEstimated bool        `json:"birth_date_estimated"`
	Status             string      `json:"status"`
	PhotoUrls          []string    `json:"photo_urls"`
	Tags               []string    `json:"tags"`
	CreatedBy          string      `json:"created_by"`
	ModifiedBy         string      `json:"modified_by"`
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error) {
	row := q.db.QueryRow(ctx, createPet,
		arg.Name,
		arg.Species,
		arg.BirthDate,
		arg.BirthDateEstimated,
		arg.Status,
		arg.PhotoUrls,
		arg.Tags,
		arg.CreatedBy,
		arg.ModifiedBy,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Species,
		&i.BirthDate,
		&i.BirthDateEstimated,
		&i.Status,
		&i.Tags,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.PhotoUrls,
	)
	return i, err
}

const deletePet = `-- name: DeletePet :execrows
DELETE FROM pets
WHERE id = $1
`

func (q *Queries) DeletePet(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPet = `-- name: GetPet :one
SELECT id, name, species, birth_date, birth_date_estimated, status, tags, created_at, modified_at, created_by, modified_by, photo_urls FROM pets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPet(ctx context.Context, id pgtype.UUID) (Pet, error) {
	row := q.db.QueryRow(ctx, getPet, id)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Species,
		&i.BirthDate,
		&i.BirthDateEstimated,
		&i.Status,
		&i.Tags,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.PhotoUrls,
	)
	return i, err
}

const listPets = `-- name: ListPets :many
WITH filtered AS (
    SELECT id, name, species, birth_date, birth_date_estimated, status, tags, created_at, modified_at, created_by, modified_by, photo_urls, COUNT(*) OVER () AS total_count
    FROM pets
    WHERE ($4::text IS NULL OR status = $4)
      AND ($5::text IS NULL OR species = $5)
)
SELECT id, name, species, birth_date, birth_date_estimated, status, tags, created_at, modified_at, created_by, modified_by, photo_urls, total_count FROM filtered
WHERE (
    $1::timestamptz IS NULL
    OR (created_at, id) < ($1::timestamptz, $2::uuid)
)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListPetsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
	Status          pgtype.Text        `json:"status"`
	Species         pgtype.Text        `json:"species"`
}

type ListPetsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Species            string             `json:"species"`
	BirthDate          pgtype.Date        `json:"birth_date"`
	BirthDateEstimated bool               `json:"birth_date_estimated"`
	Status             string             `json:"status"`
	Tags               []string           `json:"tags"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ModifiedAt         pgtype.Timestamptz `json:"modified_at"`
	CreatedBy          string             `json:"created_by"`
	ModifiedBy         string             `json:"modified_by"`
	PhotoUrls          []string           `json:"photo_urls"`
	TotalCount         int64              `json:"total_count"`
}

// Cursor paging: (created_at, id) is a total order because id is unique, so a row
// inserted between fetches cannot shift the window the way OFFSET did.
//
// COUNT(*) OVER() sits inside the CTE, over the filter-matching rows only. Putting
// it outside the cursor predicate would count the remainder after the cursor and
// silently report the wrong total. The window still scans the filtered set on every
// page, exactly as the old separate CountPets did; that is the first thing to drop
// if this table ever grows.
func (q *Queries) ListPets(ctx context.Context, arg ListPetsParams) ([]ListPetsRow, error) {
	rows, err := q.db.Query(ctx, listPets,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
		arg.Status,
		arg.Species,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPetsRow{}
	for rows.Next() {
		var i ListPetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Species,
			&i.BirthDate,
			&i.BirthDateEstimated,
			&i.Status,
			&i.Tags,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.PhotoUrls,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePet = `-- name: UpdatePet :one
UPDATE pets
SET
    name = COALESCE($1, name),
    species = COALESCE($2, species),
    birth_date = CASE WHEN $3::bool
                      THEN $4::date
                      ELSE birth_date END,
    birth_date_estimated = COALESCE($5, birth_date_estimated),
    status = COALESCE($6, status),
    photo_urls = COALESCE($7::text[], photo_urls),
    tags = COALESCE($8::text[], tags),
    modified_at = NOW(),
    modified_by = $9
WHERE id = $10
RETURNING id, name, species, birth_date, birth_date_estimated, status, tags, created_at, modified_at, created_by, modified_by, photo_urls
`

type UpdatePetParams struct {
	Name               pgtype.Text `json:"name"`
	Species            pgtype.Text `json:"species"`
	SetBirthDate       bool        `json:"set_birth_date"`
	BirthDate          pgtype.Date `json:"birth_date"`
	BirthDateEstimated pgtype.Bool `json:"birth_date_estimated"`
	Status             pgtype.Text `json:"status"`
	PhotoUrls          []string    `json:"photo_urls"`
	Tags               []string    `json:"tags"`
	ModifiedBy         string      `json:"modified_by"`
	ID                 pgtype.UUID `json:"id"`
}

// A NULL parameter means "leave this column as it is", so one statement serves
// both a partial and a full update without a read-modify-write cycle.
// birth_date needs an explicit flag rather than COALESCE because it is nullable:
// for it, NULL is a legitimate value to store, not an absence of instruction.
func (q *Queries) UpdatePet(ctx context.Context, arg UpdatePetParams) (Pet, error) {
	row := q.db.QueryRow(ctx, updatePet,
		arg.Name,
		arg.Species,
		arg.SetBirthDate,
		arg.BirthDate,
		arg.BirthDateEstimated,
		arg.Status,
		arg.PhotoUrls,
		arg.Tags,
		arg.ModifiedBy,
		arg.ID,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Species,
		&i.BirthDate,
		&i.BirthDateEstimated,
		&i.Status,
		&i.Tags,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.PhotoUrls,
	)
	return i, err
}
