// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPets = `-- name: CountPets :one
SELECT COUNT(*) FROM pets
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR species = $2)
`

type CountPetsParams struct {
	Status  pgtype.Text `json:"status"`
	Species pgtype.Text `json:"species"`
}

func (q *Queries) CountPets(ctx context.Context, arg CountPetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPets, arg.Status, arg.Species)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPet = `-- name: CreatePet :one
INSERT INTO pets (
    name, species, age, status, photo_urls, tags, created_at, modified_at, created_by, modified_by
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW(), $7, $8
)
RETURNING id, name, species, age, status, photo_urls, tags, created_at, modified_at, created_by, modified_by
`

type CreatePetParams struct {
	Name       string   `json:"name"`
	Species    string   `json:"species"`
	Age        int32    `json:"age"`
	Status     string   `json:"status"`
	PhotoUrls  []string `json:"photo_urls"`
	Tags       []string `json:"tags"`
	CreatedBy  string   `json:"created_by"`
	ModifiedBy string   `json:"modified_by"`
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error) {
	row := q.db.QueryRow(ctx, createPet,
		arg.Name,
		arg.Species,
		arg.Age,
		arg.Status,
		arg.PhotoUrls,
		arg.Tags,
		arg.CreatedBy,
		arg.ModifiedBy,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Species,
		&i.Age,
		&i.Status,
		&i.PhotoUrls,
		&i.Tags,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CreatedBy,
		&i.ModifiedBy,
	)
	return i, err
}

const deletePet = `-- name: DeletePet :exec
DELETE FROM pets
WHERE id = $1
`

func (q *Queries) DeletePet(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePet, id)
	return err
}

const getPet = `-- name: GetPet :one
SELECT id, name, species, age, status, photo_urls, tags, created_at, modified_at, created_by, modified_by FROM pets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPet(ctx context.Context, id pgtype.UUID) (Pet, error) {
	row := q.db.QueryRow(ctx, getPet, id)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Species,
		&i.Age,
		&i.Status,
		&i.PhotoUrls,
		&i.Tags,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CreatedBy,
		&i.ModifiedBy,
	)
	return i, err
}

const listPets = `-- name: ListPets :many
SELECT id, name, species, age, status, photo_urls, tags, created_at, modified_at, created_by, modified_by FROM pets
WHERE ($3::text IS NULL OR status = $3)
  AND ($4::text IS NULL OR species = $4)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPetsParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Status  pgtype.Text `json:"status"`
	Species pgtype.Text `json:"species"`
}

func (q *Queries) ListPets(ctx context.Context, arg ListPetsParams) ([]Pet, error) {
	rows, err := q.db.Query(ctx, listPets,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Species,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pet{}
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Species,
			&i.Age,
			&i.Status,
			&i.PhotoUrls,
			&i.Tags,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.CreatedBy,
			&i.ModifiedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePet = `-- name: UpdatePet :one
UPDATE pets
SET
    name = $2,
    species = $3,
    age = $4,
    status = $5,
    photo_urls = $6,
    tags = $7,
    modified_at = NOW(),
    modified_by = $8
WHERE id = $1
RETURNING id, name, species, age, status, photo_urls, tags, created_at, modified_at, created_by, modified_by
`

type UpdatePetParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Species    string      `json:"species"`
	Age        int32       `json:"age"`
	Status     string      `json:"status"`
	PhotoUrls  []string    `json:"photo_urls"`
	Tags       []string    `json:"tags"`
	ModifiedBy string      `json:"modified_by"`
}

func (q *Queries) UpdatePet(ctx context.Context, arg UpdatePetParams) (Pet, error) {
	row := q.db.QueryRow(ctx, updatePet,
		arg.ID,
		arg.Name,
		arg.Species,
		arg.Age,
		arg.Status,
		arg.PhotoUrls,
		arg.Tags,
		arg.ModifiedBy,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Species,
		&i.Age,
		&i.Status,
		&i.PhotoUrls,
		&i.Tags,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CreatedBy,
		&i.ModifiedBy,
	)
	return i, err
}
